FROM node:20-alpine

RUN npm install -g pnpm pm2 bun

WORKDIR /usr/src/app

ENV PORT=$PORT \
    NODE_ENV=${NODE_ENV} \
    JWT_EXPIRE=${JWT_EXPIRE} \
    JWT_SECRET=${JWT_SECRET} \
    POSTGRES_DATABASE=$POSTGRES_DATABASE \
    POSTGRES_HOST=$POSTGRES_HOST \
    POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    POSTGRES_USER=$POSTGRES_USER \
    POSTGRES_URL=$POSTGRES_URL \
    POSTGRES_URL_NON_POOLING=$POSTGRES_URL_NON_POOLING \
    POSTGRES_URL_NO_SSL=$POSTGRES_URL_NO_SSL \
    PUSHER_APPID=$PUSHER_APPID \
    PUSHER_KEY=$PUSHER_KEY \
    PUSHER_SECRET=$PUSHER_SECRET \
    PUSHER_CLUSTER=$PUSHER_CLUSTER

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY dist ./dist

ENV NODE_ENV=production

ENV NODE_ENV=$NODE_ENV \
    PORT=$PORT \
    JWT_EXPIRE=$JWT_EXPIRE \
    JWT_SECRET=$JWT_SECRET \
    PUSHER_APPID=$PUSHER_APPID \
    PUSHER_KEY=$PUSHER_KEY \
    PUSHER_SECRET=$PUSHER_SECRET \
    PUSHER_CLUSTER=$PUSHER_CLUSTER \
    POSTGRES_DATABASE=$POSTGRES_DATABASE \
    POSTGRES_HOST=$POSTGRES_HOST \
    POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    POSTGRES_PRISMA_URL=$POSTGRES_PRISMA_URL \
    POSTGRES_URL=$POSTGRES_URL \
    POSTGRES_URL_NON_POOLING=$POSTGRES_URL_NON_POOLING \
    POSTGRES_URL_NO_SSL=$POSTGRES_URL_NO_SSL \
    POSTGRES_USER=$POSTGRES_USER

CMD [ "pm2-runtime","src/app.ts" ]
