version: '3.8'

services:
  # express應用服務
  app:
    build:
      context: . # 指定 Dockerfile 所在的目錄
      dockerfile: Dockerfile # 指定要使用的 Dockerfile（如果名稱是 Dockerfile 可以省略這行）
    image: beast964089/vue-vite-demo-api-express:latest
    # 端口映射：主機端口:容器端口
    ports:
      - "3000:3000"
    # 環境變數設定
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      # JWT 相關設定，使用 .env 文件中的值
      - JWT_EXPIRE=${JWT_EXPIRE}
      - JWT_SECRET=${JWT_SECRET}
      # Pusher 相關設定，使用 .env 文件中的值
      - PUSHER_APPID=${PUSHER_APPID}
      - PUSHER_KEY=${PUSHER_KEY}
      - PUSHER_SECRET=${PUSHER_SECRET}
      - PUSHER_CLUSTER=${PUSHER_CLUSTER}
      # vercel postgres 相關設定，使用 .env 文件中的值
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
      - POSTGRES_URL_NO_SSL=${POSTGRES_URL_NO_SSL}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
